### ISSUE TITLE
rdbmsimage_dh_frontend_1 fails to start

### ISSUE THREAD

**Issue by iilunin** [devicehive/devicehive-docker#30]
V 3.3.0
On docker-compose up - frontend consumes abnormal amount of memory and then dies. Logs attached.
[fe_error.txt](https://github.com/devicehive/devicehive-docker/files/1240188/fe_error.txt)

**Comment by sitnik** [comment]
Hi Igor,
This is know issue with FE unable to ping BE via Kafka. From version 3.3.1 frontend (and other services as well) are restarted in case of crash.

**Comment by sitnik** [comment]
I hope your issue was resolved. Don't bother to reopen ticket if issue persists. Thank you for reporting.
