### ISSUE TITLE
mqtt-brokers.yml

### ISSUE THREAD

**Issue by wzqallz** [devicehive/devicehive-docker#51]
MQTT default connection WS_SERVER_URL is "ws://playground-dev.devicehive.com/api/websocket", how do I configure to connect my own Web Socket?
 By the way, my docker-compose.yml is the default.

**Comment by sitnik** [comment]
Hi @wzqallz, this is definitely a my mistake. I'll fix this issue shortly, will be available in next release.

**Comment by sitnik** [comment]
@wzqallz, for docker-compose installation WS_SERVER_URL values must point to internal address of DeviceHive Frontend container, i.e. "ws://dh_frontend:8080/api/websocket". This is now fixed in development branch and will be released soon.

**Comment by wzqallz** [comment]
thank you very much.

**Comment by sitnik** [comment]
Resolved in release 3.5.0
