### ISSUE TITLE
Wrong user and password Admin

### ISSUE THREAD

**Issue by rchemali** [devicehive/devicehive-docker#52]
I used the user and password as indicated in readme  but it does not work
thank you

**Comment by sitnik** [comment]
Hi @rchemali,

Password, provided in README, is default for new installations and must work. Authorization issues indicate some problems with installation which we'll try to investigate. Which installation type you are using: docker-compose or kubernetes? In case of docker-compose please provide output of following commands on server while DeviceHive started:
```
sudo docker ps
free -m
```

Another reason may be in long start of application. It tooks about minute to start all services on machine with 4 CPU cores and 8GB of RAM. Have you tried logging in after a few minutes?

**Comment by sitnik** [comment]
I found you posted the same question to DeviceHive Intercon channel with some more details.
So you are using docker-compose installation. We need output of `sudo docker ps` command to find which services doesn't work properly.
Also please provide some additional information about your environment like
# Machine parameters: CPU, RAM
# Which distirubution you are using on host machine
# Version of docker and docker-compose: `sudo docker info` and `sudo docker-compose version` output.

Thanks.

**Comment by rchemali** [comment]
I will try thank you

**Comment by rchemali** [comment]
it still does not work with : ram 8go cpu 4 
i have 9 process with docker ps 
i use windows 10
docker-compose version 1.16.1, build 6d1ac219

**Comment by rchemali** [comment]
Probléme solved thank you

**Comment by sanchez123-hub** [comment]
> Probléme solved thank you

I have the same problem.Could you tell me how did you fix it?Thank you very much.
