### ISSUE TITLE
Add requirements to charts/

### ISSUE THREAD

**Issue by iakrevetkho** [devicehive/devicehive-docker#59]
In installation progress with helm, installation fault with error: _"Can't locate requirements in folder charts/"_.
Requirements charts should be founded in folder _charts/_

**Comment by iakrevetkho** [comment]
I try to install devicehive with helm on rancher 2.0

**Comment by sitnik** [comment]
@iakrevetkho , hello.
Try running `helm dependency update ./devicehive` from devicehive/k8s directory before installation.
We currently don't provide repository with packaged DeviceHive charts which include dependencies, so `helm dependency update` must be called before `helm install`.

**Comment by sitnik** [comment]
I'm closing the issue because there is no new comments from author in more than month.
