### ISSUE TITLE
Running DeviceHive without Kafka

### ISSUE THREAD

**Issue by aldrinc** [devicehive/devicehive-docker#62]
Is there an easy way for me to run devicehive without Kafka? Can I just kill the Kafka containers without issue in production?

**Comment by amedviediev** [comment]
If you don't want to use Kafka, you can use any other message broker instead. All communication with the message broker is handled by the devicehive-ws-proxy microservice (https://github.com/devicehive/devicehive-ws-proxy). You can create your own microservice that implements the same interface and communicates with your preferred message broker, and use it instead. 
However, a message broker is required for the proper work of the system. You will not be able to disable Kafka without providing a replacement.

**Comment by sitnik** [comment]
As question is properly answered by Anton, I'm closing this issue.
